# Generated by Django 4.1.1 on 2022-09-17 08:18

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_stars_post_type_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=30)),
                ('to_name', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('time', models.DateField(auto_now_add=True)),
                ('type_message', models.IntegerField(choices=[(1, 'Happy'), (2, 'Kind'), (3, 'Angry'), (4, 'Silly')], null=True)),
            ],
        ),
    ]